### ISSUE TITLE
Fix footer to the bottom of page

### ISSUE THREAD

**Issue by RiedleroD** [VChet/StyleBase#6]
If I want to click any link in the footer, the styles begin to load and push the footer down.
The solution would be letting the footer just float at the bottom of the screen.

pseudo css code of what I mean:
```css
footer{
    position:fixed;
    bottom:0;
    left:0;
    width:100vw;}
```
